project_id = "tennis"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
site_url = "https://tennis-web-lime.vercel.app"
additional_redirect_urls = ["http://localhost:3000", "https://localhost:3000", "https://tennis-web-lime.vercel.app/**"]
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = true
client_id = "897836821938-5q6fth1p35aerfrr4lqfb91i3qga4agu.apps.googleusercontent.com"
secret = "env(GOOGLE_CLIENT_SECRET)"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
