CREATE TYPE sport_type AS ENUM ('tennis', 'padel', 'squash', 'pickleball', 'badminton');
CREATE TYPE play_format AS ENUM ('singles', 'doubles', 'mixed_doubles');
CREATE TYPE play_style AS ENUM ('recreational', 'competitive', 'both');
CREATE TYPE surface_type AS ENUM ('clay', 'hard', 'grass', 'carpet', 'synthetic');
CREATE TYPE court_environment AS ENUM ('indoor', 'outdoor');
CREATE TYPE game_status AS ENUM ('draft', 'open', 'confirmed', 'completed', 'cancelled');
CREATE TYPE booking_status AS ENUM ('pending', 'confirmed', 'cancelled', 'completed', 'refunded');
CREATE TYPE result_status AS ENUM ('pending', 'confirmed', 'disputed');
CREATE TYPE session_type AS ENUM ('individual', 'group');
CREATE TYPE tournament_format AS ENUM ('single_elimination', 'double_elimination', 'round_robin', 'ladder');
CREATE TYPE message_type AS ENUM ('text', 'game_invite', 'system', 'media');
CREATE TYPE post_type AS ENUM ('regular', 'match_result', 'achievement', 'review');
CREATE TYPE payment_status AS ENUM ('pending', 'processing', 'completed', 'failed', 'refunded');
CREATE TYPE review_target_type AS ENUM ('player', 'coach', 'club');
CREATE TYPE participant_status AS ENUM ('invited', 'accepted', 'declined', 'cancelled');
CREATE TYPE slot_status AS ENUM ('available', 'booked', 'blocked');
CREATE TYPE skill_reason AS ENUM ('match', 'tournament', 'coach_verified', 'assessment');
CREATE TYPE league_season_status AS ENUM ('upcoming', 'active', 'completed');
CREATE TYPE conversation_type AS ENUM ('direct', 'game_group', 'tournament_group');
CREATE TYPE media_type AS ENUM ('photo', 'video');
